### PR TITLE
Remove bazelrc and use proper WASM build rules

### PR DESCRIPTION
**Pull request by taegyunkim**
This lets us introduce non-WASM build targets in the same BUILD file.

### CODE REVIEW

**Comment by yuval-k** [comment]
@ilackarms can you tell why CI seems upset?/

**Comment by Sodman** [comment]
> @ilackarms can you tell why CI seems upset?/

@yuval-k this particular fail is due to skv2, but it doesn't appear to be the only thing causing the failures (happens on master too). I'm currently running through the build on my local trying to reproduce + fix.

**Comment by taegyunkim** [comment]
Do I need to do something for changelog-bot?

**Comment by yuval-k** [comment]
@taegyunkim for changelog bot, you need to add a changelog in the folder of the next release.
as 0.0.20 is out, the next release is:
https://github.com/solo-io/wasme/tree/master/changelog/v0.0.21
you can see examples in the changelog folder. i believe the right type for this change is `NON_USER_FACING` as it is build related and doesn't impact users

**Comment by yuval-k** [comment]
hi @taegyunkim do you mind merging master? we have updated it to fix the CI issue we are seeing... thank you very much!

**Comment by taegyunkim** [comment]
Done.

**Comment by taegyunkim** [comment]
I misclicked close button and reopened. Then the ci ran again and failed.  ¯\_(ツ)_/¯

**Comment by yuval-k** [comment]
i'm re-running CI to see if it's a flake. will take a deeper look if its not

**Comment by yuval-k** [comment]
@Sodman can you take a look?

**Comment by taegyunkim** [comment]
Btw, I locally ran tests via `make run-tests` and all passed. hmm

**Comment by Sodman** [comment]
There's nothing in the PR that makes me think these tests should fail. Either it's a test flake or the retry-wasm-filter-deploy feature implemented in https://github.com/solo-io/gloo/pull/3383 doesn't work as consistently at we thought. (Although that also has an e2e test which always passes as far as I'm aware). I'm going to trigger CI here again while I look into this further.

**Comment by yuval-k** [comment]
seems like it was a flake.. thank you!

**Pull request merged**
