### PR TITLE
Fix rust examples

### PR DESCRIPTION
**Pull request by corporealshift**
Add some more details to how to build wasm plugins via rust and cargo. Fixes some of the proxy function signatures to reflect what envoy expects. I used [this list](https://github.com/envoyproxy/envoy-wasm/blob/master/api/wasm/cpp/proxy_wasm_externs.h) to compare the signatures.

### CODE REVIEW

**Comment by EItanya** [comment]
This PR looks great overall, thanks again for this. Also, you will need to create a changelog entry for this PR.

The instructions to do that can be found [here](https://github.com/solo-io/go-utils/tree/master/changelogutils)

**Comment by corporealshift** [comment]
I've added a changelog file. let me know if you want me to adjust anything

**Comment by ilackarms** [comment]
@corporealshift we are not currently enforcing changelogs on the wasme repo.

/skip-changelog

thanks for this contribution!

**Pull request merged**
